id: P002914
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105846
  title: དགྲ་ལྷའི་ཁྲབ་རྫོང་།
  author: ''
  volumes:
    407db7e500cc4cdf9305d8e393740e6e:
      image_group_id: I1PD105848
      title: ''
      volume_number: 1
      total_pages: 672
      base_file: v001.txt
